### ISSUE TITLE
kodi.py doesn't import for me

### ISSUE THREAD

**Issue by marksev1** [Cadair/mycroft-kodi#3]
Hello Cadair "import kodi" doesn't work for me, any other way to do it?

**Comment by Cadair** [comment]
What are you trying to achieve? To make mycroft detect the module it needs to be in the third_party_skills directory.

**Comment by marksev1** [comment]
Oh. Id like to have it in the skills folder. Because on orangepi i use an older version of mycroft.

**Comment by Cadair** [comment]
I haven't tried with older versions of mycroft, can you just copy it into that directory? I don't really have time to work on this at the moment, but I am happy to accept patches or documentation improvements.
